### ISSUE TITLE
✨ プロジェクトのベースを作成

### ISSUE THREAD

**Issue by yuu-eguci** [scent-stuff/scent-stuff-superuser#19]
## Description 

- [x] ✨ プロジェクトのベースを作成: nuxt.config.js -> nuxt.config.ts
- [x] ✨ プロジェクトのベースを作成: JavaScript -> TypeScript https://github.com/scent-stuff/scent-stuff-superuser/issues/18
- [x] ✨ プロジェクトのベースを作成: ページ構造 pages/foo.vue -> pages/foo/index.vue
- [x] ✨ プロジェクトのベースを作成: Components -> container, presentational components
- [x] ✨ プロジェクトのベースを作成: middleware 導入
- [x] ✨ プロジェクトのベースを作成: i18n 導入 https://github.com/scent-stuff/scent-stuff-superuser/issues/16
- [ ] ✨ プロジェクトのベースを作成: CommonUtils 導入 https://github.com/scent-stuff/scent-stuff-superuser/issues/6
- [x] ✨ プロジェクトのベースを作成: 複数 .env 導入 (.env.local, .env.github-pages) https://github.com/scent-stuff/scent-stuff-superuser/issues/17
